spring.application.name=DevTrack
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:mysql://root:pIFaceqElRJRxGsBchFNTZglzLUdTicH@mainline.proxy.rlwy.net:57602/railway}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:pIFaceqElRJRxGsBchFNTZglzLUdTicH}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

devtrack.jwt.secret=${JWT_SECRET:8a34ace5e3ebf324157a7965a554da50e605ea738f0febfc914a00576b647f9b}
devtrack.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
devtrack.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:3001}
devtrack.seed.enabled=${DEVTRACK_SEED_ENABLED:true}

logging.level.com.devtrack=${LOG_LEVEL:INFO}
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html
